name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        run: python run_pipeline.py

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git clone https://KAFIL-ASLAM:${HF_TOKEN}@huggingface.co/spaces/KAFIL-ASLAM/house-price-demo hf_space

          cp -r pipeline hf_space/
          cp -r api hf_space/
          cp -r app hf_space/
          cp -r data hf_space/
          cp config.yaml hf_space/
          cp Dockerfile hf_space/
          cp requirements.txt hf_space/
          cp run_pipeline.py hf_space/

          cd hf_space
          git add .
          git commit -m "deploy from github actions" || echo "nothing to commit"
          git push